version: "3.7"
services:
  app_proxy:
    environment:
      # Format: <app-id>_<service-name>_1
      APP_HOST: ronschronsch-btc-checker_server_1
      APP_PORT: 34277

  server:
    build: .
    restart: on-failure
    user: "1000:1000"
    init: true
    volumes:
      - ${APP_DATA_DIR}/data:/data
