name: Build & Push Docker

on:
  push:
    branches: [ master ]
    tags:     [ 'v*' ]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Compute Tag
        id: meta
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          else
            echo "TAG=latest" >> $GITHUB_OUTPUT
          fi

      - name: Build & Push (ronschlabs/btc-checker)
        uses: docker/build-push-action@v6
        with:
          context: ./ronschlabs-btc-checker
          push: true
          tags: |
            ronschlabs/btc-checker:${{ steps.meta.outputs.TAG }}
            ronschlabs/btc-checker:latest
